name: Deploying exp-ui
on:
  push:
    branches:
    - main
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploying changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTENDHOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd beckn-exp-ui
          git stash
          git checkout main
          git pull
          npm install
          npm run build
          sleep 10
          pm2 kill
          #pm2 serve build 3000 --spa
          pm2 start --name=exp-ui  npm -- start
